"""Where every third-party credential added by the feature expansion is read from.

TWO SCOPES, ONE STORE
Every secret lives in `integration_tokens`, Fernet-encrypted, written only by
app/integrations/token_store.py::TokenStore. That is a hard requirement for
everything added after M9, and it is why none of the providers below has an
environment variable: a key in the environment is a key in every process
listing, every crash dump and every `docker inspect`.

  user scope    user_id = <the user>. OAuth grants (Slack, HubSpot,
                Salesforce), a user's own LinkedIn account id, their own
                overriding API key. Belongs to one account, deleted with it.
  system scope  user_id = NULL. Deployment-wide API keys the operator pays
                for (OpenAI for the consensus engine, NewsAPI, Vapi,
                ElevenLabs, MXToolbox, Mailreach) and the OAuth *app*
                credentials (client id/secret) every user's grant is minted
                against. Set from the admin panel (/admin/integrations).

`get_secret` tries the user's own credential first and falls back to the
system one, so an agency that brings its own NewsAPI key uses it, and every
other account rides on the deployment's.

NOTHING HERE EVER RETURNS A SECRET TO AN HTTP CLIENT. `status()` reports which
keys are SET, never their values -- the admin page renders a checkmark, not a
masked string, because a masked string still leaks length and prefix.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass

from sqlalchemy.orm import Session

from app.core.exceptions import ClientHunterError
from app.integrations.token_store import TokenStore


class IntegrationNotConfigured(ClientHunterError):
    """A feature needs a credential nobody has set.

    Callers turn this into a soft outcome (the brief says "no news found",
    the channel reports "not connected") rather than a 500: an unconfigured
    optional integration is a deployment state, not an error.
    """

    def __init__(self, provider: str, key: str):
        self.provider = provider
        self.key = key
        super().__init__(
            f"{provider} is not configured ({key} is not set) -- an admin can "
            f"set it under Admin > Integrations"
        )


@dataclass(frozen=True)
class ProviderSpec:
    provider: str
    label: str
    keys: tuple[str, ...]
    purpose: str
    # "system": only the admin sets it. "user": only a user connects it (an
    # OAuth grant). "both": a system default a user may override.
    scope: str
    # Keys the admin MAY set that `configured` does not require (e.g. the
    # Unipile account used to READ LinkedIn posts when a user has not
    # connected their own).
    optional: tuple[str, ...] = ()


# The catalogue the admin page renders. A provider missing from here can still
# be stored, but it will not appear in the UI -- so every integration added by
# the feature expansion is listed, with the one sentence an operator needs to
# decide whether to pay for it.
CATALOGUE: tuple[ProviderSpec, ...] = (
    ProviderSpec("openai", "OpenAI", ("api_key",),
                 "Second model for the multi-model strategy consensus engine "
                 "(GPT-4o). Without it, strategies are generated by Claude "
                 "alone and carry no uncertain zones.", "system"),
    ProviderSpec("newsapi", "NewsAPI", ("api_key",),
                 "Recent company news injected into outreach hooks and the "
                 "meeting prep brief.", "both"),
    ProviderSpec("unipile", "Unipile", ("api_key", "dsn"),
                 "LinkedIn post fetching and the LinkedIn outreach channel "
                 "(connection requests, messages, InMail). `dsn` is your "
                 "Unipile API host, e.g. api8.unipile.com:13851. "
                 "`reader_account_id` (optional) is the Unipile LinkedIn "
                 "account used to read posts for users who have not "
                 "connected their own. `webhook_secret` authenticates "
                 "Unipile's deliveries to /webhooks/unipile (set the same "
                 "value as the webhook's Unipile-Auth header).", "system",
                 optional=("reader_account_id", "webhook_secret")),
    ProviderSpec("rapidapi_linkedin", "RapidAPI LinkedIn scraper",
                 ("api_key", "host"),
                 "Fallback for LinkedIn post fetching when Unipile is not "
                 "configured.", "system"),
    ProviderSpec("loom", "Loom", ("public_app_id",),
                 "Loom recordSDK app id used to build the personalised video "
                 "CTA for high-scoring leads.", "system"),
    ProviderSpec("vapi", "Vapi.ai", ("api_key", "phone_number_id"),
                 "AI outbound cold calling (PhoneChannel). `webhook_secret` "
                 "is sent by Vapi as x-vapi-secret on end-of-call reports.",
                 "both", optional=("webhook_secret",)),
    ProviderSpec("elevenlabs", "ElevenLabs", ("api_key", "voice_id"),
                 "Voicemail audio (TTS) and the calling fallback. The "
                 "fallback also needs `agent_id` and `agent_phone_number_id` "
                 "(a Conversational AI agent); `webhook_secret` verifies its "
                 "post-call webhook.", "both",
                 optional=("agent_id", "agent_phone_number_id", "webhook_secret")),
    ProviderSpec("slack_app", "Slack app", ("client_id", "client_secret",
                                             "signing_secret"),
                 "The Slack app every user's 'Connect Slack' grant is minted "
                 "against.", "system"),
    ProviderSpec("hubspot_app", "HubSpot app", ("client_id", "client_secret"),
                 "The HubSpot public app behind 'Connect HubSpot'. The client "
                 "secret also verifies HubSpot webhook signatures.", "system"),
    ProviderSpec("salesforce_app", "Salesforce connected app",
                 ("client_id", "client_secret", "webhook_secret"),
                 "The Salesforce connected app behind 'Connect Salesforce', "
                 "and the shared secret its outbound-message relay signs "
                 "with.", "system"),
    ProviderSpec("mxtoolbox", "MXToolbox", ("api_key",),
                 "Daily sending-domain blacklist checks. Without it the check "
                 "falls back to direct DNSBL lookups.", "system"),
    ProviderSpec("mailreach", "Mailreach", ("api_key",),
                 "Email account health: spam score, inbox placement, "
                 "SPF/DKIM/DMARC.", "both"),
)

_BY_PROVIDER = {spec.provider: spec for spec in CATALOGUE}


def spec_for(provider: str) -> ProviderSpec | None:
    return _BY_PROVIDER.get(provider)


def get_secret(db: Session, provider: str, key: str,
               user_id: uuid.UUID | str | None = None) -> str | None:
    """The user's own credential, else the deployment's, else None."""
    if user_id is not None:
        value = TokenStore.get(db, user_id=user_id, provider=provider, key=key)
        if value:
            return value
    return TokenStore.get(db, user_id=None, provider=provider, key=key) or None


def require_secret(db: Session, provider: str, key: str,
                   user_id: uuid.UUID | str | None = None) -> str:
    value = get_secret(db, provider, key, user_id=user_id)
    if not value:
        raise IntegrationNotConfigured(provider, key)
    return value


def is_configured(db: Session, provider: str,
                  user_id: uuid.UUID | str | None = None) -> bool:
    """True when EVERY key the catalogue lists for `provider` resolves."""
    spec = spec_for(provider)
    keys = spec.keys if spec else ()
    return bool(keys) and all(get_secret(db, provider, k, user_id=user_id)
                              for k in keys)


def set_system_secret(db: Session, provider: str, key: str, value: str) -> None:
    TokenStore.set(db, user_id=None, provider=provider, key=key, value=value)


def delete_system_secret(db: Session, provider: str, key: str | None = None) -> int:
    return TokenStore.delete(db, user_id=None, provider=provider, key=key)


def system_status(db: Session) -> list[dict]:
    """Catalogue + which keys are set. Values are never included."""
    out = []
    for spec in CATALOGUE:
        present = set(TokenStore.keys(db, user_id=None, provider=spec.provider))
        out.append({
            "provider": spec.provider,
            "label": spec.label,
            "purpose": spec.purpose,
            "scope": spec.scope,
            "keys": ([{"key": k, "is_set": k in present, "optional": False}
                      for k in spec.keys]
                     + [{"key": k, "is_set": k in present, "optional": True}
                        for k in spec.optional]),
            "configured": all(k in present for k in spec.keys),
        })
    return out
