"""Message personalization — every outgoing message is generated by Claude
from the strategy's Phase-6 messaging research + the lead's enrichment,
guided by the sequence step's brief. The rendered subject/body are
persisted on the message row BEFORE any send happens.
"""

import logging

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import Lead, PipelineKind, ResearchStep, SequenceStep, Strategy
from app.services.anthropic_client import get_client

logger = logging.getLogger(__name__)

_SYSTEM = (
    "You are LeadPilot's message personalization engine. You write one "
    "concise, specific, non-spammy B2B outreach email for one lead, "
    "following the messaging playbook and the step brief. Respond with "
    'ONLY a JSON object: {"subject": "...", "body": "..."} — no prose, '
    "no markdown fences. The body is plain text, under 140 words, no "
    "placeholders like [Name] (use the actual data given), and does NOT "
    "include an unsubscribe footer (the system appends the compliant "
    "footer itself)."
)

_PROMPT = """SEQUENCE STEP #{step_no} BRIEF (variant {variant}):
{template}

MESSAGING PLAYBOOK (from strategy research, phase 6):
{playbook}

LEAD:
- Name: {full_name}
- Title: {title}
- Company: {company}
- Enrichment highlights: {enrichment}

{booking_line}
Write the email for THIS lead now."""


def _playbook(session: Session, strategy: Strategy) -> str:
    rows = session.execute(
        select(ResearchStep).where(
            ResearchStep.strategy_id == strategy.id,
            ResearchStep.pipeline == PipelineKind.STRATEGY,
            ResearchStep.phase == 6,
            ResearchStep.step_no % 9 == 0,  # phase-6 synthesis
        )
    ).scalars().all()
    return "\n\n".join(r.output for r in rows) or "(no messaging research found — keep it short, factual and human)"


def render_message(
    session: Session,
    strategy: Strategy,
    lead: Lead,
    step: SequenceStep,
    booking_url: str | None = None,
) -> tuple[str, str]:
    """Returns (subject, body) — the caller persists them before sending."""
    enrichment = lead.enrichment_json or {}
    highlights = {
        k: enrichment.get(k)
        for k in ("company_domain", "enrichment")
        if enrichment.get(k)
    }
    booking_line = (
        f"Include this scheduling link naturally in the call to action: {booking_url}\n"
        if booking_url else ""
    )
    data = get_client().complete_json(
        system=_SYSTEM,
        prompt=_PROMPT.format(
            step_no=step.step_no,
            variant=step.variant,
            template=step.template,
            playbook=_playbook(session, strategy),
            full_name=lead.full_name or "there",
            title=lead.title or "unknown",
            company=lead.company or "their company",
            enrichment=str(highlights)[:1500],
            booking_line=booking_line,
        ),
    )
    subject = str(data.get("subject") or "").strip() or "Quick question"
    body = str(data.get("body") or "").strip()
    if not body:
        raise ValueError("personalization returned an empty body")
    return subject, body


# --------------------------------------------------------------------------
# WhatsApp template variables (M4 Chunk 3)
# --------------------------------------------------------------------------

_WA_SYSTEM = (
    "You are LeadPilot's WhatsApp template variable filler. You produce "
    "SHORT values for numbered template variables, from real lead data and "
    "the messaging playbook. Respond with ONLY a JSON object mapping each "
    'requested variable number to its value, e.g. {"1": "Sara", "2": '
    '"Acme\'s slow onboarding"}. Values must be plain text, a few words '
    "each, honest, drawn only from the data given — never invented facts, "
    "names, or statistics."
)

_WA_PROMPT = """TEMPLATE BODY (for context — do NOT rewrite it):
{body}

VARIABLES TO FILL (number -> what it means / brief):
{briefs}

MESSAGING PLAYBOOK (strategy research, phase 6):
{playbook}

LEAD:
- Name: {full_name}
- Title: {title}
- Company: {company}
- Enrichment highlights: {enrichment}

Return the JSON object of values now."""

# Deterministic 'lead.<field>' sources — no model call needed for these.
_LEAD_FIELDS = {
    "lead.full_name": lambda lead: lead.full_name,
    "lead.first_name": lambda lead: (lead.full_name or "").split(" ")[0],
    "lead.title": lambda lead: lead.title,
    "lead.company": lambda lead: lead.company,
    "lead.email": lambda lead: lead.email,
}


def render_whatsapp_variables(
    session: Session,
    strategy: Strategy,
    lead: Lead,
    template_body: str,
    variable_descriptions: dict,
    variable_mapping: dict | None,
) -> dict[str, str]:
    """Values for every {{n}} in an approved template.

    mapping semantics (per variable number, from the sequence step):
      'lead.<field>'  -> filled deterministically from the lead row
      anything else   -> treated as a brief; Claude fills it from lead
                         enrichment + the strategy's messaging playbook
      missing mapping -> the template's own variable description is the brief
    Same personalization path as M3 email — one model call for all briefs.
    Raises ValueError when a variable cannot be filled (caller fails the
    send rather than transmitting a template with empty slots)."""
    mapping = {str(k): str(v) for k, v in (variable_mapping or {}).items()}
    numbers = sorted(variable_descriptions or {}, key=lambda n: int(n))

    values: dict[str, str] = {}
    briefs: dict[str, str] = {}
    for n in numbers:
        source = mapping.get(n, "").strip()
        if source in _LEAD_FIELDS:
            value = (_LEAD_FIELDS[source](lead) or "").strip()
            if value:
                values[n] = value
                continue
            # Empty lead field degrades to a brief, not an empty variable.
            source = ""
        briefs[n] = source or str(variable_descriptions.get(n, f"variable {n}"))

    if briefs:
        enrichment = lead.enrichment_json or {}
        data = get_client().complete_json(
            system=_WA_SYSTEM,
            prompt=_WA_PROMPT.format(
                body=template_body,
                briefs="\n".join(f"{{{{{n}}}}} -> {b}" for n, b in briefs.items()),
                playbook=_playbook(session, strategy),
                full_name=lead.full_name or "unknown",
                title=lead.title or "unknown",
                company=lead.company or "unknown",
                enrichment=str(enrichment)[:1500],
            ),
        )
        for n in briefs:
            value = str(data.get(n) or "").strip()
            if not value:
                raise ValueError(f"could not fill template variable {{{{{n}}}}}")
            values[n] = value

    missing = [n for n in numbers if n not in values]
    if missing:
        raise ValueError(f"unfilled template variables: {missing}")
    return values


def preview_whatsapp_body(template_body: str, values: dict[str, str]) -> str:
    """The human-readable rendered body persisted on the message row."""
    out = template_body
    for n, v in values.items():
        out = out.replace("{{%s}}" % n, v)
    return out
