"""Message personalization — every outgoing message is generated by Claude
from the strategy's Phase-6 messaging research + the lead's enrichment,
guided by the sequence step's brief. The rendered subject/body are
persisted on the message row BEFORE any send happens.
"""

import logging

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import Lead, PipelineKind, ResearchStep, SequenceStep, Strategy
from app.services.anthropic_client import get_client

logger = logging.getLogger(__name__)

_SYSTEM = (
    "You are LeadPilot's message personalization engine. You write one "
    "concise, specific, non-spammy B2B outreach email for one lead, "
    "following the messaging playbook and the step brief. Respond with "
    'ONLY a JSON object: {"subject": "...", "body": "..."} — no prose, '
    "no markdown fences. The body is plain text, under 140 words, no "
    "placeholders like [Name] (use the actual data given), and does NOT "
    "include an unsubscribe footer (the system appends the compliant "
    "footer itself)."
)

_PROMPT = """SEQUENCE STEP #{step_no} BRIEF (variant {variant}):
{template}

MESSAGING PLAYBOOK (from strategy research, phase 6):
{playbook}

LEAD:
- Name: {full_name}
- Title: {title}
- Company: {company}
- Enrichment highlights: {enrichment}

{context}{booking_line}
Write the email for THIS lead now."""


def _playbook(session: Session, strategy: Strategy) -> str:
    rows = session.execute(
        select(ResearchStep).where(
            ResearchStep.strategy_id == strategy.id,
            ResearchStep.pipeline == PipelineKind.STRATEGY,
            ResearchStep.phase == 6,
            ResearchStep.step_no % 9 == 0,  # phase-6 synthesis
        )
    ).scalars().all()
    research = ("\n\n".join(r.output for r in rows)
                or "(no messaging research found — keep it short, factual and human)")
    mutation = _applied_mutation(session, strategy)
    return f"{mutation}\n\n{research}" if mutation else research


def _voice(session: Session, strategy: Strategy) -> str:
    from app.services.style_profile import suffix_for_strategy  # noqa: PLC0415

    return suffix_for_strategy(session, strategy)


def _applied_mutation(session: Session, strategy: Strategy) -> str | None:
    """Feature Group 1: the messaging of an APPLIED strategy mutation.

    Outreach is personalised from the phase-6 research above, not from
    strategy_document -- so applying a mutation by rewriting the document
    alone would have changed nothing a lead ever receives. The applied
    version's new angle and revised messaging are therefore put in front of
    the research here, marked as taking precedence where they conflict. A
    proposed (unapplied) mutation has no effect.
    """
    from app.db.models import StrategyVersion  # noqa: PLC0415

    version = session.execute(
        select(StrategyVersion)
        .where(StrategyVersion.strategy_id == strategy.id,
               StrategyVersion.status == "applied",
               StrategyVersion.trigger != "original")
        .order_by(StrategyVersion.version_no.desc())
    ).scalars().first()
    if version is None:
        return None
    changes = version.changes_json or {}
    angle = (changes.get("messaging_angle") or {}).get("proposed") or ""
    revised = changes.get("revised_messaging") or ""
    return (f"[APPLIED STRATEGY MUTATION v{version.version_no} — takes precedence "
            f"over the research below where they conflict]\n"
            f"Messaging angle: {angle}\n{revised}").strip()


def render_message(
    session: Session,
    strategy: Strategy,
    lead: Lead,
    step: SequenceStep,
    booking_url: str | None = None,
    inputs_out: dict | None = None,
) -> tuple[str, str]:
    """Returns (subject, body) — the caller persists them before sending.

    Feature Group 2: the prompt carries the lead's recent LinkedIn posts and
    company news (personalization_context), the personal-video CTA on step 2
    when one was recorded (loom_video), and the system prompt carries the
    sender's voice profile (style_profile). `inputs_out`, when given, is
    filled with what the message was written from, for messages.personalization_json.
    """
    from app.services import loom_video, personalization_context, style_profile  # noqa: PLC0415

    enrichment = lead.enrichment_json or {}
    highlights = {
        k: enrichment.get(k)
        for k in ("company_domain", "enrichment")
        if enrichment.get(k)
    }
    booking_line = (
        f"Include this scheduling link naturally in the call to action: {booking_url}\n"
        if booking_url else ""
    )
    context, used = personalization_context.prompt_block(lead)
    cta = loom_video.cta_for_step(lead, step.step_no)
    used["loom_cta"] = bool(cta)
    if cta:
        context = f"{context}\n\n{cta}".strip()
    voice = style_profile.suffix_for_strategy(session, strategy)
    used["style_profile"] = bool(voice)
    if inputs_out is not None:
        inputs_out.update(used)
    data = get_client().complete_json(
        system=_SYSTEM + voice,
        prompt=_PROMPT.format(
            context=f"{context}\n\n" if context else "",
            step_no=step.step_no,
            variant=step.variant,
            template=step.template,
            playbook=_playbook(session, strategy),
            full_name=lead.full_name or "there",
            title=lead.title or "unknown",
            company=lead.company or "their company",
            enrichment=str(highlights)[:1500],
            booking_line=booking_line,
        ),
    )
    subject = str(data.get("subject") or "").strip() or "Quick question"
    body = str(data.get("body") or "").strip()
    if not body:
        raise ValueError("personalization returned an empty body")
    return subject, body


# --------------------------------------------------------------------------
# WhatsApp template variables (M4 Chunk 3)
# --------------------------------------------------------------------------

_WA_SYSTEM = (
    "You are LeadPilot's WhatsApp template variable filler. You produce "
    "SHORT values for numbered template variables, from real lead data and "
    "the messaging playbook. Respond with ONLY a JSON object mapping each "
    'requested variable number to its value, e.g. {"1": "Sara", "2": '
    '"Acme\'s slow onboarding"}. Values must be plain text, a few words '
    "each, honest, drawn only from the data given — never invented facts, "
    "names, or statistics."
)

_WA_PROMPT = """TEMPLATE BODY (for context — do NOT rewrite it):
{body}

VARIABLES TO FILL (number -> what it means / brief):
{briefs}

MESSAGING PLAYBOOK (strategy research, phase 6):
{playbook}

LEAD:
- Name: {full_name}
- Title: {title}
- Company: {company}
- Enrichment highlights: {enrichment}

Return the JSON object of values now."""

# Deterministic 'lead.<field>' sources — no model call needed for these.
_LEAD_FIELDS = {
    "lead.full_name": lambda lead: lead.full_name,
    "lead.first_name": lambda lead: (lead.full_name or "").split(" ")[0],
    "lead.title": lambda lead: lead.title,
    "lead.company": lambda lead: lead.company,
    "lead.email": lambda lead: lead.email,
}


def render_whatsapp_variables(
    session: Session,
    strategy: Strategy,
    lead: Lead,
    template_body: str,
    variable_descriptions: dict,
    variable_mapping: dict | None,
) -> dict[str, str]:
    """Values for every {{n}} in an approved template.

    mapping semantics (per variable number, from the sequence step):
      'lead.<field>'  -> filled deterministically from the lead row
      anything else   -> treated as a brief; Claude fills it from lead
                         enrichment + the strategy's messaging playbook
      missing mapping -> the template's own variable description is the brief
    Same personalization path as M3 email — one model call for all briefs.
    Raises ValueError when a variable cannot be filled (caller fails the
    send rather than transmitting a template with empty slots)."""
    mapping = {str(k): str(v) for k, v in (variable_mapping or {}).items()}
    numbers = sorted(variable_descriptions or {}, key=lambda n: int(n))

    values: dict[str, str] = {}
    briefs: dict[str, str] = {}
    for n in numbers:
        source = mapping.get(n, "").strip()
        if source in _LEAD_FIELDS:
            value = (_LEAD_FIELDS[source](lead) or "").strip()
            if value:
                values[n] = value
                continue
            # Empty lead field degrades to a brief, not an empty variable.
            source = ""
        briefs[n] = source or str(variable_descriptions.get(n, f"variable {n}"))

    if briefs:
        enrichment = lead.enrichment_json or {}
        data = get_client().complete_json(
            # Feature Group 2: the sender's voice, like every outreach copy call.
            system=_WA_SYSTEM + _voice(session, strategy),
            prompt=_WA_PROMPT.format(
                body=template_body,
                briefs="\n".join(f"{{{{{n}}}}} -> {b}" for n, b in briefs.items()),
                playbook=_playbook(session, strategy),
                full_name=lead.full_name or "unknown",
                title=lead.title or "unknown",
                company=lead.company or "unknown",
                enrichment=str(enrichment)[:1500],
            ),
        )
        for n in briefs:
            value = str(data.get(n) or "").strip()
            if not value:
                raise ValueError(f"could not fill template variable {{{{{n}}}}}")
            values[n] = value

    missing = [n for n in numbers if n not in values]
    if missing:
        raise ValueError(f"unfilled template variables: {missing}")
    return values


def preview_whatsapp_body(template_body: str, values: dict[str, str]) -> str:
    """The human-readable rendered body persisted on the message row."""
    out = template_body
    for n, v in values.items():
        out = out.replace("{{%s}}" % n, v)
    return out


# --------------------------------------------------------------------------
# Engagement Hub, Feature 1 — the auto follow-up brief
# --------------------------------------------------------------------------
#
# WHY THIS RETURNS A BRIEF AND NOT A FINISHED MESSAGE
# Every message in this system is a two-stage thing: a sequence step holds a
# BRIEF ("open on their hiring post, ask one question about onboarding"), and
# render_message above turns the brief plus the lead's data plus the strategy's
# messaging playbook into the copy that actually sends. That split is what lets
# the send path re-render at send time, after the compliance gates, with the
# playbook as it stands today.
#
# An auto follow-up that produced finished copy here would sit outside all of
# that: it would be written hours before it sends, against whatever the
# playbook said then, and it would bypass the personalization scoring and the
# compliant-email assembly that only run on the render path. So this generates
# the missing BRIEF -- the thing a human would have written as step N+1 -- and
# the ordinary send path does the rest.
#
# It costs one extra model call per auto follow-up. That is the price of the
# follow-up being indistinguishable from a step somebody wrote.

_FOLLOWUP_SYSTEM = (
    "You are LeadPilot's follow-up brief writer. A prospect was contacted and "
    "has not replied. You write the BRIEF for the next touch -- instructions "
    "to the message writer, not the message itself. Respond with ONLY a JSON "
    'object: {"brief": "..."} -- no prose, no markdown fences.\n'
    "RULES. The brief is 1-3 sentences. It must name the angle to take and "
    "the single question to ask. It must be grounded ONLY in the history and "
    "product brief given -- never invent a trigger event, a mutual "
    "connection, a statistic or a deadline. Do not suggest guilt, urgency, "
    "'just bumping this to the top of your inbox', 'circling back', or any "
    "reference to the prospect not having replied. Assume they never saw the "
    "first message."
)

_FOLLOWUP_PROMPT = """WHAT WAS SENT BEFORE (most recent last):
{history}

WHAT THIS PROSPECT HAS DONE (outcome log):
{outcomes}

WHAT WE SELL:
{product}

MESSAGING PLAYBOOK (strategy research, phase 6):
{playbook}

LEAD:
- Name: {full_name}
- Title: {title}
- Company: {company}

CHANNEL FOR THIS FOLLOW-UP: {channel}

Write the brief for the next touch now."""

# Used when the model call fails. A generic brief still produces a message the
# render path will personalize from real lead data, which is a far better
# outcome than a follow-up that silently never sends because Anthropic was
# briefly down.
FALLBACK_FOLLOWUP_BRIEF = (
    "Short, friendly follow-up on the previous message. Restate the single "
    "most relevant benefit for this company in one line and ask one specific, "
    "easy-to-answer question. No pressure, no reference to them not replying."
)


def build_followup_brief(
    session: Session,
    strategy: Strategy,
    lead: Lead,
    *,
    channel: str = "email",
    max_history: int = 3,
) -> str:
    """The brief for an automatic follow-up, from this lead's actual history.

    Never raises. A follow-up whose brief could not be generated falls back to
    FALLBACK_FOLLOWUP_BRIEF rather than failing the send: the render path will
    still personalize it against the lead's real data and the playbook, so the
    degraded case is a less specific message, not a wrong one and not a
    missing one.
    """
    from app.db.models import Message, Outcome, Product  # noqa: PLC0415

    sent = session.execute(
        select(Message)
        .where(Message.lead_id == lead.id, Message.body.isnot(None))
        .order_by(Message.step_no)
    ).scalars().all()[-max_history:]
    history = "\n\n".join(
        f"[step {m.step_no}, {m.channel.value if m.channel else '?'}] "
        f"{(m.subject or '').strip()}\n{(m.body or '').strip()[:600]}"
        for m in sent
    ) or "(nothing on file — treat this as a first touch)"

    events = session.execute(
        select(Outcome)
        .where(Outcome.lead_id == lead.id)
        .order_by(Outcome.ts)
    ).scalars().all()[-12:]
    outcomes = ", ".join(
        f"{o.event.value if o.event else '?'}"
        f"({o.channel}{', ' + o.ts.date().isoformat() if o.ts else ''})"
        for o in events
    ) or "(no recorded activity)"

    product = session.get(Product, strategy.product_id)
    product_brief = (
        f"{product.name} — {product.description or ''}".strip(" —")
        if product is not None else "(no product on file)"
    )

    try:
        data = get_client().complete_json(
            system=_FOLLOWUP_SYSTEM,
            prompt=_FOLLOWUP_PROMPT.format(
                history=history[:6000],
                outcomes=outcomes,
                product=product_brief[:1000],
                playbook=_playbook(session, strategy)[:4000],
                full_name=lead.full_name or "there",
                title=lead.title or "unknown",
                company=lead.company or "their company",
                channel=channel,
            ),
        )
        brief = str((data or {}).get("brief") or "").strip()
    except Exception as exc:  # noqa: BLE001 — see the docstring
        logger.warning("follow-up brief generation failed for lead %s: %s: %s",
                       lead.id, type(exc).__name__, exc)
        brief = ""

    return brief[:2000] or FALLBACK_FOLLOWUP_BRIEF
