"""initial models

Revision ID: 89e3b2b1d5fd
Revises: 
Create Date: 2026-08-15 16:39:58.616740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial_models"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern_key', sa.String(length=200), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_scores')),
    sa.UniqueConstraint('pattern_key', 'metric', name='pattern_metric')
    )
    op.create_index(op.f('ix_playbook_scores_pattern_key'), 'playbook_scores', ['pattern_key'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(email IS NOT NULL) OR (phone IS NOT NULL)', name=op.f('ck_suppression_list_email_or_phone_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_list'))
    )
    op.create_index(op.f('ix_suppression_list_email'), 'suppression_list', ['email'], unique=True)
    op.create_index(op.f('ix_suppression_list_phone'), 'suppression_list', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plantier', native_enum=False, length=32), nullable=False),
    sa.Column('theme_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('product', 'skill', name='producttype', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_products_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('past_clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('acquisition_story', sa.Text(), nullable=False),
    sa.Column('extracted_patterns_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_past_clients_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_past_clients'))
    )
    op.create_index(op.f('ix_past_clients_product_id'), 'past_clients', ['product_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.Enum('with_clients', 'no_clients', name='flowtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'researching', 'verifying', 'verified', 'needs_human_review', 'executing', 'failed', name='strategystatus', native_enum=False, length=32), nullable=False),
    sa.Column('verified_passes_json', sa.JSON(), nullable=False),
    sa.Column('strategy_document', sa.Text(), nullable=True),
    sa.Column('gtm_document', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_strategies_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_product_id'), 'strategies', ['product_id'], unique=False)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('enrichment_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('sourced', 'enriched', 'email_found', 'verified', 'flagged', 'dropped', 'contacted', 'replied', 'meeting_booked', name='leadstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_leads_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('strategy_id', 'email', name='strategy_email'),
    sa.UniqueConstraint('strategy_id', 'source', 'external_id', name='strategy_source_external')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_strategy_id'), 'leads', ['strategy_id'], unique=False)
    op.create_table('research_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline', sa.Enum('strategy', 'gtm', name='pipelinekind', native_enum=False, length=32), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_research_steps_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_steps')),
    sa.UniqueConstraint('strategy_id', 'pipeline', 'step_no', name='strategy_pipeline_step')
    )
    op.create_index(op.f('ix_research_steps_strategy_id'), 'research_steps', ['strategy_id'], unique=False)
    op.create_index('ix_research_steps_strategy_phase', 'research_steps', ['strategy_id', 'pipeline', 'phase'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'linkedin', name='channeltype', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='sequencestatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_sequences_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequences'))
    )
    op.create_index(op.f('ix_sequences_strategy_id'), 'sequences', ['strategy_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'linkedin', name='channeltype', native_enum=False, length=32), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'sent', 'failed', 'cancelled', name='messagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_messages_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_messages_sequence_id_sequences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_messages_sequence_id'), 'messages', ['sequence_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.Enum('sent', 'opened', 'replied', 'booked', 'won', 'lost', 'bounced', 'unsubscribed', name='outcomeevent', native_enum=False, length=32), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_outcomes_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_outcomes_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_index('ix_outcomes_lead_event', 'outcomes', ['lead_id', 'event'], unique=False)
    op.create_index(op.f('ix_outcomes_lead_id'), 'outcomes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_lead_id'), table_name='outcomes')
    op.drop_index('ix_outcomes_lead_event', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_messages_sequence_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sequences_strategy_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index('ix_research_steps_strategy_phase', table_name='research_steps')
    op.drop_index(op.f('ix_research_steps_strategy_id'), table_name='research_steps')
    op.drop_table('research_steps')
    op.drop_index(op.f('ix_leads_strategy_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_product_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_past_clients_product_id'), table_name='past_clients')
    op.drop_table('past_clients')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_list_phone'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_email'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_playbook_scores_pattern_key'), table_name='playbook_scores')
    op.drop_table('playbook_scores')
    # ### end Alembic commands ###
