"""lead batches

Revision ID: e7ff61ea20e5
Revises: 0001_initial_models
Create Date: 2026-08-15 16:59:28.009193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_lead_batches'
down_revision: Union[str, None] = '0001_initial_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('sourcing', 'enriching', 'finding_emails', 'verifying', 'finalized', 'failed', name='batchstage', native_enum=False, length=32), nullable=False),
    sa.Column('requested_leads', sa.Integer(), nullable=False),
    sa.Column('icp_criteria_json', sa.JSON(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('verifier_provider', sa.String(length=50), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_lead_batches_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_batches'))
    )
    op.create_index(op.f('ix_lead_batches_stage'), 'lead_batches', ['stage'], unique=False)
    op.create_index(op.f('ix_lead_batches_strategy_id'), 'lead_batches', ['strategy_id'], unique=False)
    # batch mode: SQLite (tests) needs copy-and-move for ALTERs; on
    # Postgres this degrades to plain ALTER TABLE statements.
    with op.batch_alter_table('leads') as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_batch_id'), ['batch_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_leads_batch_id_lead_batches'),
            'lead_batches', ['batch_id'], ['id'], ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_batch_id_lead_batches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_batch_id'))
        batch_op.drop_column('batch_id')
    op.drop_index(op.f('ix_lead_batches_strategy_id'), table_name='lead_batches')
    op.drop_index(op.f('ix_lead_batches_stage'), table_name='lead_batches')
    op.drop_table('lead_batches')
    # ### end Alembic commands ###
