"""outreach engine

Revision ID: ab4901e9fbd3
Revises: 0003_gmail_accounts
Create Date: 2026-08-15 17:17:12.127405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_outreach_engine'
down_revision: Union[str, None] = '0003_gmail_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_webhooks')),
    sa.UniqueConstraint('provider', 'event_id', name='provider_event')
    )
    op.create_table('sequence_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_sequence_steps_sequence_id_sequences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequence_steps')),
    sa.UniqueConstraint('sequence_id', 'step_no', name='sequence_step')
    )
    op.create_index(op.f('ix_sequence_steps_sequence_id'), 'sequence_steps', ['sequence_id'], unique=False)
    op.create_table('sequence_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'stopped', 'completed', name='enrollmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_sequence_enrollments_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_sequence_enrollments_sequence_id_sequences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequence_enrollments')),
    sa.UniqueConstraint('sequence_id', 'lead_id', name='sequence_lead')
    )
    op.create_index(op.f('ix_sequence_enrollments_lead_id'), 'sequence_enrollments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_sequence_id'), 'sequence_enrollments', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_status'), 'sequence_enrollments', ['status'], unique=False)
    op.create_table('inbound_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('account_ref', sa.String(length=64), nullable=True),
    sa.Column('thread_ref', sa.String(length=128), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_inbound_replies_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_inbound_replies_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_replies'))
    )
    op.create_index(op.f('ix_inbound_replies_lead_id'), 'inbound_replies', ['lead_id'], unique=False)
    op.add_column('gmail_accounts', sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('step_no', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('subject', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('provider_message_id', sa.String(length=128), nullable=True))
    op.add_column('messages', sa.Column('thread_ref', sa.String(length=128), nullable=True))
    op.add_column('messages', sa.Column('unsubscribe_token', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('sender_ref', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('sequences', sa.Column('booking_url', sa.String(length=500), nullable=True))
    op.add_column('strategies', sa.Column('campaign_state', sa.String(length=30), nullable=False))
    op.add_column('strategies', sa.Column('campaign_pause_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'campaign_pause_reason')
    op.drop_column('strategies', 'campaign_state')
    op.drop_column('sequences', 'booking_url')
    op.drop_column('messages', 'error')
    op.drop_column('messages', 'sender_ref')
    op.drop_column('messages', 'unsubscribe_token')
    op.drop_column('messages', 'thread_ref')
    op.drop_column('messages', 'provider_message_id')
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'subject')
    op.drop_column('messages', 'step_no')
    op.drop_column('gmail_accounts', 'last_poll_at')
    op.drop_index(op.f('ix_inbound_replies_lead_id'), table_name='inbound_replies')
    op.drop_table('inbound_replies')
    op.drop_index(op.f('ix_sequence_enrollments_status'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_sequence_id'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_lead_id'), table_name='sequence_enrollments')
    op.drop_table('sequence_enrollments')
    op.drop_index(op.f('ix_sequence_steps_sequence_id'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_table('processed_webhooks')
    # ### end Alembic commands ###
