"""M8-C1/C2: learning loop schema — outcomes dimensions, playbook reshape,
strategy promotion columns, integration_tokens table.

Revision ID: 0008_m8c2
Revises: 0009_device_tokens
Create Date: 2026-08-16 23:00:00.000000

INTEGRATION NOTE (combined build): the migration file for M8 Chunks 1+2 was
in the m8-chunks-1-2 delivery zip, which was not part of the combined-build
uploads. Migration 0009_m8c3 declares `down_revision = "0008_m8c2"`, so this
file recreates that revision. Its ID intentionally sorts before 0009 in the
directory listing but chains AFTER 0009_device_tokens — Alembic orders by the
revision graph, not by filename. Do NOT edit this file after it has been
applied anywhere; new changes → new migration.

Changes:
  1. outcomes: + strategy_id (FK strategies, SET NULL), + variant
     — denormalized dimensions so the nightly aggregation and the A/B sweep
       GROUP BY strategy/variant without 3-table joins. Outcomes are an
       immutable event log; these snapshot values at event time.
  2. strategies: + pattern_key (SHA-256 of sorted canonical JSON),
     + default_variant (set by auto-promotion; future renders only —
       in-flight messages where sent_at IS NOT NULL are never modified).
  3. playbook_scores: reshaped from (pattern_key, metric) scalar rows to
     per-variant rows — + variant, reply_rate, booking_rate, is_reliable,
     last_aggregated_at; metric → nullable; unique key becomes
     (pattern_key, variant). Existing M1 rows keep variant='A'.
  4. integration_tokens table (plaintext `value` column here; 0009_m8c3 adds
     `encrypted_value` and backfills).
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = "0008_m8c2"
down_revision = "0009_device_tokens"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── 1. outcomes: learning-loop dimensions ────────────────────────────
    op.add_column("outcomes", sa.Column("strategy_id", sa.Uuid(), nullable=True))
    op.add_column("outcomes", sa.Column("variant", sa.String(20), nullable=True))
    op.create_foreign_key(
        op.f("fk_outcomes_strategy_id_strategies"),
        "outcomes", "strategies", ["strategy_id"], ["id"], ondelete="SET NULL",
    )
    op.create_index(op.f("ix_outcomes_strategy_id"), "outcomes", ["strategy_id"])
    op.create_index(op.f("ix_outcomes_variant"), "outcomes", ["variant"])

    # Backfill strategy_id + variant for existing outcomes via their lead/message.
    op.execute("""
        UPDATE outcomes o
        SET strategy_id = l.strategy_id
        FROM leads l
        WHERE o.lead_id = l.id AND o.strategy_id IS NULL
    """)
    op.execute("""
        UPDATE outcomes o
        SET variant = m.variant
        FROM messages m
        WHERE o.message_id = m.id AND o.variant IS NULL
    """)

    # ── 2. strategies: pattern key + promoted variant ────────────────────
    op.add_column("strategies", sa.Column("pattern_key", sa.String(200), nullable=True))
    op.add_column("strategies", sa.Column("default_variant", sa.String(20), nullable=True))
    op.create_index(op.f("ix_strategies_pattern_key"), "strategies", ["pattern_key"])

    # ── 3. playbook_scores: per-variant reshape ──────────────────────────
    op.add_column("playbook_scores",
                  sa.Column("variant", sa.String(20), nullable=False, server_default="A"))
    op.add_column("playbook_scores", sa.Column("reply_rate", sa.Float(), nullable=True))
    op.add_column("playbook_scores", sa.Column("booking_rate", sa.Float(), nullable=True))
    op.add_column("playbook_scores",
                  sa.Column("is_reliable", sa.Boolean(), nullable=False, server_default="false"))
    op.add_column("playbook_scores",
                  sa.Column("last_aggregated_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("playbook_scores", "metric",
                    existing_type=sa.String(50), nullable=True)
    # M1 unique key (pattern_key, metric) → (pattern_key, variant).
    op.drop_constraint("pattern_metric", "playbook_scores", type_="unique")
    op.create_unique_constraint("pattern_variant", "playbook_scores",
                                ["pattern_key", "variant"])

    # ── 4. integration_tokens ────────────────────────────────────────────
    op.create_table(
        "integration_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(40), nullable=False),
        sa.Column("token_kind", sa.String(40), nullable=False, server_default="api_key"),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE",
                                name=op.f("fk_integration_tokens_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_tokens")),
        sa.UniqueConstraint("user_id", "provider", "token_kind",
                            name="user_provider_kind"),
    )
    op.create_index(op.f("ix_integration_tokens_user_id"),
                    "integration_tokens", ["user_id"])
    op.create_index(op.f("ix_integration_tokens_provider"),
                    "integration_tokens", ["provider"])


def downgrade() -> None:
    op.drop_index(op.f("ix_integration_tokens_provider"), table_name="integration_tokens")
    op.drop_index(op.f("ix_integration_tokens_user_id"), table_name="integration_tokens")
    op.drop_table("integration_tokens")

    op.drop_constraint("pattern_variant", "playbook_scores", type_="unique")
    op.create_unique_constraint("pattern_metric", "playbook_scores",
                                ["pattern_key", "metric"])
    op.alter_column("playbook_scores", "metric",
                    existing_type=sa.String(50), nullable=False)
    op.drop_column("playbook_scores", "last_aggregated_at")
    op.drop_column("playbook_scores", "is_reliable")
    op.drop_column("playbook_scores", "booking_rate")
    op.drop_column("playbook_scores", "reply_rate")
    op.drop_column("playbook_scores", "variant")

    op.drop_index(op.f("ix_strategies_pattern_key"), table_name="strategies")
    op.drop_column("strategies", "default_variant")
    op.drop_column("strategies", "pattern_key")

    op.drop_index(op.f("ix_outcomes_variant"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_strategy_id"), table_name="outcomes")
    op.drop_constraint(op.f("fk_outcomes_strategy_id_strategies"),
                       "outcomes", type_="foreignkey")
    op.drop_column("outcomes", "variant")
    op.drop_column("outcomes", "strategy_id")
