"""``clienthunter serve`` — self-host the backend stack via Docker Compose.

    clienthunter serve [--detach]     # start the full stack
    clienthunter serve stop           # stop all containers
    clienthunter serve logs           # tail container logs

⚠  Self-hosted mode: campaigns run ONLY while this machine is on.
   For 24/7 operation, deploy the same compose stack to a cloud server.
   See: https://docs.clienthunter.ai/deploy

Requirements:
    Docker Desktop or Docker Engine must be installed and running.
    This command does NOT install Docker — if it's missing, it tells you
    where to get it and exits clearly.

How it works:
    1. Checks that ``docker`` and ``docker compose`` are available.
    2. Looks for ``docker-compose.yml`` in the current directory.
       If not found, writes a ready-to-use template to
       ``~/.clienthunter/serve/docker-compose.yml`` and uses that.
    3. Prompts for required secrets (Anthropic API key), generates
       strong defaults for the rest, and writes ``.env``.
    4. Runs ``docker compose up`` (blocking) or ``up -d`` (--detach).
    5. Waits for the backend health endpoint, then prints URLs.
"""
from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import time
from pathlib import Path
from typing import Optional

import typer
from rich.prompt import Confirm, Prompt

from clienthunter.cli._console import _get_client, console, err_console
from clienthunter.config import _CONFIG_DIR

# ---------------------------------------------------------------------------
# Typer sub-app
# ---------------------------------------------------------------------------

serve_app = typer.Typer(
    name="serve",
    help="Self-host the backend stack via Docker Compose.",
    invoke_without_command=True,
)

_SERVE_DIR = _CONFIG_DIR / "serve"
_BUNDLED_COMPOSE = _SERVE_DIR / "docker-compose.yml"
_HEALTH_TIMEOUT = 90   # seconds to wait for healthy backend
_HEALTH_INTERVAL = 3

# ---------------------------------------------------------------------------
# Docker-compose template (used when no compose file found in CWD)
# ---------------------------------------------------------------------------

_COMPOSE_TEMPLATE = """\
# ClientHunter self-hosted stack
# Generated by `clienthunter serve`
# For 24/7 campaigns, deploy this to a cloud server instead of running locally.
# Docs: https://docs.clienthunter.ai/deploy

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.workers.celery_app worker -l info -c 4
    env_file: .env
    depends_on: [backend]
    restart: unless-stopped

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.workers.celery_app beat -l info
    env_file: .env
    depends_on: [backend]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ch
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: clienthunter
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ch -d clienthunter"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
"""

# ---------------------------------------------------------------------------
# .env template
# ---------------------------------------------------------------------------

_ENV_TEMPLATE = """\
# ClientHunter backend environment — generated by `clienthunter serve`
# Keep this file secret; never commit it to version control.

DATABASE_URL=postgresql://ch:{POSTGRES_PASSWORD}@db:5432/clienthunter
REDIS_URL=redis://redis:6379/0
SECRET_KEY={SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=30

# Anthropic (required)
ANTHROPIC_API_KEY={ANTHROPIC_API_KEY}

# Apollo.io — Lead sourcing (optional; lead sourcing disabled if absent)
APOLLO_API_KEY={APOLLO_API_KEY}

# Hunter.io — Email verification (optional)
HUNTER_API_KEY={HUNTER_API_KEY}

# WhatsApp Business Cloud API (optional)
WHATSAPP_PHONE_NUMBER_ID={WHATSAPP_PHONE_NUMBER_ID}
WHATSAPP_ACCESS_TOKEN={WHATSAPP_ACCESS_TOKEN}
WHATSAPP_VERIFY_TOKEN={WHATSAPP_VERIFY_TOKEN}

# Calendly (optional)
CALENDLY_WEBHOOK_SECRET={CALENDLY_WEBHOOK_SECRET}

# Gmail OAuth (optional; see docs for setup)
GMAIL_CLIENT_ID={GMAIL_CLIENT_ID}
GMAIL_CLIENT_SECRET={GMAIL_CLIENT_SECRET}

# Compliance
POSTGRES_PASSWORD={POSTGRES_PASSWORD}
LEADS_MAX_PER_RUN=200
BOUNCE_RATE_PAUSE_THRESHOLD=0.03
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _check_docker() -> bool:
    """Return True if Docker is installed and the daemon is running."""
    if shutil.which("docker") is None:
        return False
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True, timeout=10
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _check_compose(compose_file: Path) -> bool:
    """Return True if docker compose v2 is available."""
    try:
        result = subprocess.run(
            ["docker", "compose", "--file", str(compose_file), "ps"],
            capture_output=True, timeout=10
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _find_compose_file() -> Path | None:
    """Look for docker-compose.yml in CWD first, then bundled location."""
    cwd_compose = Path.cwd() / "docker-compose.yml"
    if cwd_compose.exists():
        return cwd_compose
    if _BUNDLED_COMPOSE.exists():
        return _BUNDLED_COMPOSE
    return None


def _write_compose_template() -> Path:
    """Write the bundled compose template to ~/.clienthunter/serve/."""
    _SERVE_DIR.mkdir(parents=True, exist_ok=True)
    _BUNDLED_COMPOSE.write_text(_COMPOSE_TEMPLATE, encoding="utf-8")
    return _BUNDLED_COMPOSE


def _env_file_for(compose_file: Path) -> Path:
    return compose_file.parent / ".env"


def _generate_env(env_path: Path) -> None:
    """Prompt for required secrets, generate strong defaults, write .env."""
    console.print("\n[bold]Configure secrets[/bold]")
    console.print("[muted]Required secrets are prompted; others get safe generated defaults.[/muted]\n")

    anthropic_key = Prompt.ask(
        "[bold]ANTHROPIC_API_KEY[/bold] [red](required)[/red]",
        password=True,
    )
    if not anthropic_key.strip():
        err_console.print("[error]ANTHROPIC_API_KEY is required — the pipeline cannot run without it.[/error]")
        raise typer.Exit(1)

    apollo_key = Prompt.ask("APOLLO_API_KEY (leave blank to skip)", default="", password=True)
    hunter_key = Prompt.ask("HUNTER_API_KEY (leave blank to skip)", default="", password=True)

    wa_phone = Prompt.ask("WHATSAPP_PHONE_NUMBER_ID (leave blank to skip)", default="")
    wa_token = ""
    wa_verify = ""
    if wa_phone:
        wa_token = Prompt.ask("WHATSAPP_ACCESS_TOKEN", password=True)
        wa_verify = secrets.token_hex(16)

    calendly_secret = Prompt.ask("CALENDLY_WEBHOOK_SECRET (leave blank to skip)", default="", password=True)
    gmail_id = Prompt.ask("GMAIL_CLIENT_ID (leave blank to skip)", default="")
    gmail_secret = ""
    if gmail_id:
        gmail_secret = Prompt.ask("GMAIL_CLIENT_SECRET", password=True)

    postgres_pw = secrets.token_urlsafe(24)
    secret_key = secrets.token_hex(32)

    env_content = _ENV_TEMPLATE.format(
        POSTGRES_PASSWORD=postgres_pw,
        SECRET_KEY=secret_key,
        ANTHROPIC_API_KEY=anthropic_key,
        APOLLO_API_KEY=apollo_key or "not_configured",
        HUNTER_API_KEY=hunter_key or "not_configured",
        WHATSAPP_PHONE_NUMBER_ID=wa_phone or "not_configured",
        WHATSAPP_ACCESS_TOKEN=wa_token or "not_configured",
        WHATSAPP_VERIFY_TOKEN=wa_verify or secrets.token_hex(16),
        CALENDLY_WEBHOOK_SECRET=calendly_secret or secrets.token_hex(16),
        GMAIL_CLIENT_ID=gmail_id or "not_configured",
        GMAIL_CLIENT_SECRET=gmail_secret or "not_configured",
    )

    env_path.write_text(env_content, encoding="utf-8")
    os.chmod(env_path, 0o600)
    console.print(f"[success]✓ .env written to {env_path} (mode 0600)[/success]")


def _wait_for_health(api_url: str = "http://localhost:8000") -> bool:
    """Poll /health until the backend responds or timeout."""
    import urllib.request
    deadline = time.time() + _HEALTH_TIMEOUT
    while time.time() < deadline:
        try:
            urllib.request.urlopen(f"{api_url}/health", timeout=3)
            return True
        except Exception:
            time.sleep(_HEALTH_INTERVAL)
    return False


def _run_compose(compose_file: Path, *args: str) -> int:
    """Run `docker compose --file <file> <args>` and stream output."""
    cmd = ["docker", "compose", "--file", str(compose_file), *args]
    console.print(f"[muted]$ {' '.join(cmd)}[/muted]\n")
    proc = subprocess.run(cmd)
    return proc.returncode


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@serve_app.callback(invoke_without_command=True)
def serve(
    ctx: typer.Context,
    detach: bool = typer.Option(False, "--detach", "-d",
                                help="Run containers in the background."),
) -> None:
    """Start the ClientHunter backend stack on this machine via Docker Compose.

    \b
    ⚠  Self-hosted mode: campaigns run only while THIS machine is on.
       For 24/7 operation, deploy the compose stack to a cloud server.
       See: https://docs.clienthunter.ai/deploy
    """
    if ctx.invoked_subcommand is not None:
        return  # a subcommand (stop / logs) was invoked

    console.rule("[bold]ClientHunter[/bold] — Self-Host Setup")

    # --- Docker check ---
    with console.status("[info]Checking Docker…[/info]"):
        docker_ok = _check_docker()

    if not docker_ok:
        err_console.print(
            "[error]✗ Docker is not installed or not running.[/error]\n\n"
            "Install Docker Desktop (Mac/Windows) or Docker Engine (Linux):\n"
            "  https://docs.docker.com/get-docker/\n\n"
            "After installing, ensure the Docker daemon is running, then retry.\n\n"
            "[muted]Note: `clienthunter serve` requires Docker — it does not install "
            "FastAPI, Celery, or other server dependencies inside Python.  "
            "All server logic runs in Docker containers.[/muted]"
        )
        raise typer.Exit(1)

    console.print("[success]✓ Docker is running.[/success]")

    # --- Find or create compose file ---
    compose_file = _find_compose_file()
    if compose_file is None:
        console.print(
            f"\n[muted]No docker-compose.yml found in {Path.cwd()}.[/muted]\n"
            f"Writing a ready-to-use template to {_BUNDLED_COMPOSE}…"
        )
        compose_file = _write_compose_template()
        console.print(f"[success]✓ Template written.[/success]")
        console.print(
            f"[warning]Note:[/warning] The template uses [bold]build: .[/bold] — "
            f"run from the repo root so Docker can build the images."
        )
    else:
        console.print(f"[success]✓ Using compose file:[/success] {compose_file}")

    # --- Generate .env if missing ---
    env_path = _env_file_for(compose_file)
    if env_path.exists():
        if not Confirm.ask(f"\n.env already exists at {env_path}. Regenerate?", default=False):
            console.print("[muted]Using existing .env.[/muted]")
        else:
            _generate_env(env_path)
    else:
        _generate_env(env_path)

    # --- Start stack ---
    console.print("\n[info]Starting containers…[/info] (first run may take a few minutes to build)")
    up_args = ["up", "--build"]
    if detach:
        up_args.append("-d")

    rc = _run_compose(compose_file, *up_args)
    if rc != 0 and not detach:
        raise typer.Exit(rc)

    if detach:
        # Wait for health
        console.print("\n[info]Waiting for backend to be ready…[/info]")
        if _wait_for_health():
            console.print("\n[success]✓ Stack is up![/success]")
            _print_urls()
        else:
            err_console.print(
                "[warning]⚠ Backend did not become healthy within "
                f"{_HEALTH_TIMEOUT}s.[/warning]\n"
                "Check logs: [bold]clienthunter serve logs[/bold]"
            )
            raise typer.Exit(1)


@serve_app.command("stop")
def serve_stop() -> None:
    """Stop all running ClientHunter containers."""
    compose_file = _find_compose_file()
    if compose_file is None:
        err_console.print("[error]No docker-compose.yml found. Run from the repo root or after `clienthunter serve`.[/error]")
        raise typer.Exit(1)
    rc = _run_compose(compose_file, "down")
    if rc == 0:
        console.print("[success]✓ Stack stopped.[/success]")
    raise typer.Exit(rc)


@serve_app.command("logs")
def serve_logs(
    service: Optional[str] = typer.Argument(None, help="Service name (backend/worker/beat/db/redis). Omit for all."),
    follow: bool = typer.Option(True, "--follow/--no-follow", "-f/-F"),
    tail: int = typer.Option(50, "--tail", "-n", help="Lines of log history."),
) -> None:
    """Tail logs from one or all containers."""
    compose_file = _find_compose_file()
    if compose_file is None:
        err_console.print("[error]No docker-compose.yml found.[/error]")
        raise typer.Exit(1)

    args = ["logs", f"--tail={tail}"]
    if follow:
        args.append("-f")
    if service:
        args.append(service)

    rc = _run_compose(compose_file, *args)
    raise typer.Exit(rc)


def _print_urls() -> None:
    console.print()
    console.print("  [bold]Backend API:[/bold]  http://localhost:8000")
    console.print("  [bold]API Docs:[/bold]    http://localhost:8000/docs")
    console.print("  [bold]Frontend:[/bold]    http://localhost:3000")
    console.print()
    console.print("Connect the SDK: [bold]clienthunter init[/bold]  (use http://localhost:8000 as API URL)")
    console.print("Stop the stack:  [bold]clienthunter serve stop[/bold]")
    console.print()
    console.print(
        "[warning]⚠  Campaigns run only while this machine is on.[/warning]\n"
        "   For 24/7 operation: [link=https://docs.clienthunter.ai/deploy]https://docs.clienthunter.ai/deploy[/link]"
    )
